name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Run-Test-Configuration:
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: BlandineScott/Demo@main
        with:
          DryRun: false
          serverURL: http://5cd151jqn2:8000
          testconfigID: "382edf10-de99-4c2a-abd9-bf6ddcdef474"
          ClientID: "3b5db329-0792-4995-86e6-f06fb66687cf"
          Clientsecret: "3gJzKlBXIAniIw8zJRrjujwPnSmIwqDf"
