name: "YOUR WORK FLOW NAME"

# Configure which branch that will trigger Eggplant DAI GitHub Action
# on:
#  push:
#    branches:
#      - main 
#  pull_request:
#    branches:
#      - main

jobs:
  Run-DAI-Test-Configuration:
    strategy: # Optional configuration by using matrix strategy
      max-parallel: 1 # To set the maximum number of jobs that can run simultaneously 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Operating support by Eggplant DAI GitHub Action
    runs-on: ${{ matrix.os }} # Provide OS matrix

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.5
        with:
          serverURL: "https://eval.dai.eggplant.cloud/controller/runner"
          testConfigID: "a53e535a-80f3-41e6-9797-8c8f2ba53f1e"
          Clientsecret: "6GfNG3cFcXQIluNFSMAUDnkLUmUBa4mS"
          testEnvironmentTimeout: 50
